-- fin_aiwh :: account bootstrap
-- Run once as ACCOUNTADMIN in a Snowflake worksheet.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS FIN_AIWH_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'fin_aiwh PoC compute';

CREATE DATABASE IF NOT EXISTS FIN_AIWH COMMENT = 'AI enabled finance warehouse PoC';

CREATE SCHEMA IF NOT EXISTS FIN_AIWH.RAW      COMMENT = 'Landed source data, contract governed';
CREATE SCHEMA IF NOT EXISTS FIN_AIWH.STAGING  COMMENT = 'dbt staging models';
CREATE SCHEMA IF NOT EXISTS FIN_AIWH.MARTS    COMMENT = 'dbt marts';
CREATE SCHEMA IF NOT EXISTS FIN_AIWH.META     COMMENT = 'Control plane: contracts, drift events, run log';
CREATE SCHEMA IF NOT EXISTS FIN_AIWH.CI       COMMENT = 'Ephemeral CI build target';

CREATE ROLE IF NOT EXISTS FIN_AIWH_ENG COMMENT = 'fin_aiwh engineering and automation role';

GRANT USAGE, OPERATE ON WAREHOUSE FIN_AIWH_WH TO ROLE FIN_AIWH_ENG;
GRANT USAGE ON DATABASE FIN_AIWH TO ROLE FIN_AIWH_ENG;
GRANT ALL ON SCHEMA FIN_AIWH.RAW     TO ROLE FIN_AIWH_ENG;
GRANT ALL ON SCHEMA FIN_AIWH.STAGING TO ROLE FIN_AIWH_ENG;
GRANT ALL ON SCHEMA FIN_AIWH.MARTS   TO ROLE FIN_AIWH_ENG;
GRANT ALL ON SCHEMA FIN_AIWH.META    TO ROLE FIN_AIWH_ENG;
GRANT ALL ON SCHEMA FIN_AIWH.CI      TO ROLE FIN_AIWH_ENG;
GRANT ALL ON FUTURE TABLES IN DATABASE FIN_AIWH TO ROLE FIN_AIWH_ENG;
GRANT ALL ON FUTURE VIEWS  IN DATABASE FIN_AIWH TO ROLE FIN_AIWH_ENG;

-- Service user with key pair auth. No password login.
CREATE USER IF NOT EXISTS FIN_AIWH_SVC
  DEFAULT_ROLE = FIN_AIWH_ENG
  DEFAULT_WAREHOUSE = FIN_AIWH_WH
  DEFAULT_NAMESPACE = FIN_AIWH.META
  TYPE = SERVICE
  COMMENT = 'fin_aiwh automation service user';

GRANT ROLE FIN_AIWH_ENG TO USER FIN_AIWH_SVC;
GRANT ROLE FIN_AIWH_ENG TO ROLE SYSADMIN;

-- Public key is injected by ops/sql/00_bootstrap_key.sql (generated locally, not committed).
