-- Adds downstream impact to drift events.
-- Safe to re-run. New installs get this from 01_meta_control_plane.sql.
ALTER TABLE FIN_AIWH.META.DRIFT_EVENT ADD COLUMN IF NOT EXISTS IMPACT VARIANT;

CREATE OR REPLACE VIEW FIN_AIWH.META.OPEN_DRIFT AS
SELECT DATASET_KEY, CHANGE_TYPE, SEVERITY, OBJECT_NAME, RATIONALE,
       IMPACT:marts        AS AFFECTED_MARTS,
       IMPACT:models       AS AFFECTED_MODELS,
       DETECTED_AT, EVENT_ID
FROM FIN_AIWH.META.DRIFT_EVENT
WHERE STATUS = 'OPEN'
ORDER BY CASE SEVERITY WHEN 'BREAKING' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END, DETECTED_AT;
