"""Emit the RAW DDL and the v1 data contracts from seeds/_spec.py.

Run once at bootstrap. After that, contracts are edited by hand through pull
requests and the DDL is whatever upstream actually does to the warehouse.
"""
import os, re, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _spec

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_type(ddl_type: str) -> dict:
    """Map a DDL type to how Snowflake's INFORMATION_SCHEMA will report it."""
    m = re.match(r"VARCHAR\((\d+)\)$", ddl_type)
    if m:
        return {"type": "TEXT", "length": int(m.group(1))}
    m = re.match(r"NUMBER\((\d+),(\d+)\)$", ddl_type)
    if m:
        return {"type": "NUMBER", "precision": int(m.group(1)), "scale": int(m.group(2))}
    if ddl_type in ("DATE", "BOOLEAN", "TIMESTAMP_NTZ", "FLOAT"):
        return {"type": ddl_type}
    raise ValueError(f"unmapped type: {ddl_type}")


def emit_ddl() -> str:
    out = [
        "-- fin_aiwh :: RAW layer, version 1",
        "-- Generated by seeds/emit.py. This is the starting shape of the source data.",
        "-- Upstream teams change it freely after this point; that is the point.",
        "",
        "-- Every name is fully qualified. A bare CREATE TABLE lands in whatever schema",
        "-- the session happens to be in, which for the service user is META.",
        "",
    ]
    for name, d in _spec.DATASETS.items():
        out.append(f"-- {d['description']}")
        out.append(f"CREATE OR REPLACE TABLE FIN_AIWH.RAW.{name} (")
        width = max(len(c[0]) for c in d["columns"])
        twidth = max(len(c[1]) for c in d["columns"])
        rows = []
        for col, typ, nullable, desc in d["columns"]:
            null = "" if nullable else " NOT NULL"
            rows.append(
                f"    {col.ljust(width)}  {typ.ljust(twidth)}{null}"
                f"{'' if nullable else ''}  COMMENT '{desc.replace(chr(39), chr(39)*2)}'"
            )
        out.append(",\n".join(rows))
        out.append(f") COMMENT = '{d['description']}';")
        out.append("")
    return "\n".join(out)


def emit_contract(name: str, d: dict) -> str:
    lines = [
        "# fin_aiwh data contract",
        "#",
        "# This file is the agreement, not a description. The warehouse is compared",
        "# against it on every detector run. Changing it is a reviewed pull request.",
        "",
        f"dataset: RAW.{name}",
        "version: 1",
        f"owner: {_spec.OWNER}",
        f"classification: {_spec.CLASSIFICATION}",
        f"description: {d['description']}",
        "",
        "primary_key:",
    ]
    lines += [f"  - {k}" for k in d["primary_key"]]
    lines += [
        "",
        "freshness:",
        "  column: LOADED_AT",
        "  max_lag_hours: 24",
        "",
        "# Columns the contract guarantees. A column present here and missing in the",
        "# warehouse is a break. A column in the warehouse and missing here is",
        "# ungoverned and must be adopted or rejected explicitly.",
        "columns:",
    ]
    for col, typ, nullable, desc in d["columns"]:
        t = parse_type(typ)
        lines.append(f"  - name: {col}")
        lines.append(f"    type: {t['type']}")
        if "length" in t:
            lines.append(f"    length: {t['length']}")
        if "precision" in t:
            lines.append(f"    precision: {t['precision']}")
            lines.append(f"    scale: {t['scale']}")
        lines.append(f"    nullable: {str(nullable).lower()}")
        lines.append(f"    description: {desc}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    ddl_path = os.path.join(ROOT, "ops", "sql", "02_raw_tables.sql")
    with open(ddl_path, "w") as f:
        f.write(emit_ddl())
    print("wrote", os.path.relpath(ddl_path, ROOT))

    cdir = os.path.join(ROOT, "contracts", "raw")
    os.makedirs(cdir, exist_ok=True)
    for name, d in _spec.DATASETS.items():
        p = os.path.join(cdir, f"{name.lower()}.yml")
        with open(p, "w") as f:
            f.write(emit_contract(name, d))
        print("wrote", os.path.relpath(p, ROOT))
